name: Build GKI Kernels With KernelSU-Next & SUSFS

on:
  push:  # Triggered on push to any branch or specific branches if you wish
    branches:
      - main  # Example: Only trigger on push to 'main' branch, or adjust to your needs
      - '*/*'  # Optionally, you can add wildcard to trigger on any branch
  workflow_dispatch:  # Manually triggered workflow

jobs:
  # Build Android 12 GKI Kernel
  build-kernel-a12:
    uses: ./.github/workflows/build-kernel-a12.yml  # Reference the build workflow you created for Android 12 GKI
    secrets: inherit  # Inherit any secrets you need (if required)

  # Other steps of your release workflow (e.g., packaging, deployment, etc.)
  # Add additional steps here if needed
  # e.g., upload artifacts, deploy, etc.
