name: Build GKI Kernels With KernelSU-Next & SUSFS

on:
  push:
    branches:
      - main
      - '*/*'  # Optional: Trigger on any branch
  workflow_dispatch:
    inputs:
      lto_type:
        description: 'Choose LTO type (thin/full)'
        required: true
        default: 'thin'
        type: choice
        options:
          - thin
          - full

jobs:
  # Build Android 12 GKI Kernel
  build-kernel-a12:
    uses: ./.github/workflows/build-kernel-a12.yml  # Reference the build workflow for Android 12 GKI
    with:
      lto_type: ${{ inputs.lto_type }}  # Pass the selected LTO type to the job
    secrets: inherit  # Inherit any secrets you need (if required)

  # Other jobs or steps of your release workflow (e.g., packaging, deployment, etc.)
  # Add additional steps here if needed
  # e.g., upload artifacts, deploy, etc.
