name: Build GKI Kernels With KernelSU-Next & SUSFS

on:
  push:
    branches:
      - main
      - '*/*'  # Optional: Trigger on any branch
  workflow_dispatch:
    inputs:
      lto_type:
        description: 'Choose LTO type (thin/full)'
        required: true
        default: 'thin'
        type: choice
        options:
          - thin
          - full

jobs:
  # Build Android 12 GKI Kernel
  build-kernel-a12:
    uses: ./.github/workflows/build-kernel-a12.yml  # Reference the build workflow for Android 12 GKI
    with:
      lto_type: ${{ inputs.lto_type }}  # Pass the selected LTO type to the job
    secrets: inherit  # Inherit any secrets you need (if required)

  # Build Android 13 GKI Kernel
  build-kernel-a13:
    uses: ./.github/workflows/build-kernel-a13.yml  # Reference the build workflow for Android 13 GKI
    with:
      lto_type: ${{ inputs.lto_type }}  # Pass the selected LTO type to the job
    secrets: inherit  # Inherit any secrets you need (if required)

  # Build Android 14 GKI Kernel
  build-kernel-a14:
    uses: ./.github/workflows/build-kernel-a14.yml  # Reference the build workflow for Android 14 GKI
    with:
      lto_type: ${{ inputs.lto_type }}  # Pass the selected LTO type to the job
    secrets: inherit  # Inherit any secrets you need (if required)

  # Trigger Release Job
  trigger-release:
    runs-on: ubuntu-latest
    needs: [build-kernel-a12, build-kernel-a13, build-kernel-a14]  # Ensure this job runs only after the kernel build jobs complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Release Workflow
        uses: ./.github/workflows/release.yml  # Call the release.yml workflow
