name: Build GKI Kernels With KernelSU-Next & SUSFS

on:
  workflow_dispatch:  # Allows triggering manually from the GitHub Actions UI
  push:  # Allows triggering on push to the repository
    branches:
      - main  # Only triggers on pushes to the 'main' branch

jobs:
  # Build Android 12 GKI Kernel
  build-kernel-a12:
    uses: ./.github/workflows/build-kernel-a12.yml
    secrets: inherit

  # Build Android 13 GKI Kernel
  build-kernel-a13:
    uses: ./.github/workflows/build-kernel-a13.yml
    secrets: inherit

  # Build Android 14 GKI Kernel
  build-kernel-a14:
    uses: ./.github/workflows/build-kernel-a14.yml
    secrets: inherit

  # Trigger Release Job
  trigger-release:
    runs-on: ubuntu-latest
    needs:
      - build-kernel-a12
      - build-kernel-a13
      - build-kernel-a14
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Release Workflow
        uses: ./.github/workflows/release.yml
