name: Test GLIBC Version

on:
  workflow_dispatch:  # Manual trigger for this workflow

jobs:
  test-glibc-version:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04

    steps:
    - name: Check GLIBC version
      run: |
        echo "[+] Checking GLIBC version"
        ldd --version
