name: Release

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  # Build Android 12 GKI Kernel
  build-kernel-a12:
    uses: ./.github/workflows/build-kernel-a12.yml  # Reference the build workflow you created for Android 12 GKI
    secrets: inherit  # Inherit any secrets you need (if required)

  # Other steps of your release workflow (e.g., packaging, deployment, etc.)
  # Add additional steps here if needed
  # e.g., upload artifacts, deploy, etc.
